name: Run Telegram AutoForward Bot

on:
  schedule:
    - cron: "0 * * * *"  # Jalan tiap jam
  workflow_dispatch:  # Bisa dijalankan manual

jobs:
  run-bot:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v3
        with:
          python-version: "3.9"

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Set environment variables
        run: |
          echo "TELEGRAM_API_ID=${{ secrets.TELEGRAM_API_ID }}" >> $GITHUB_ENV
          echo "TELEGRAM_API_HASH=${{ secrets.TELEGRAM_API_HASH }}" >> $GITHUB_ENV
          echo "TWITTER_API_KEY=${{ secrets.TWITTER_API_KEY }}" >> $GITHUB_ENV
          echo "TWITTER_API_SECRET=${{ secrets.TWITTER_API_SECRET }}" >> $GITHUB_ENV
          echo "TWITTER_ACCESS_TOKEN=${{ secrets.TWITTER_ACCESS_TOKEN }}" >> $GITHUB_ENV
          echo "TWITTER_ACCESS_SECRET=${{ secrets.TWITTER_ACCESS_SECRET }}" >> $GITHUB_ENV
          echo "OPENAI_API_KEY=${{ secrets.OPENAI_API_KEY }}" >> $GITHUB_ENV
          echo "CHANNEL_USERNAME=${{ secrets.CHANNEL_USERNAME }}" >> $GITHUB_ENV

      - name: Run script
        run: python src/main.py

